from .product import Product
from .category import Category
from .processor import Processor
from .harddisk import HardDisk
from .gpu import GPU
from .storage import Storage
from .ram import RAM
from .display import Display
from .costumer import Costumer
from .orders import Order