# Generated by Django 3.2 on 2021-04-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.display'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.gpu'),
        ),
        migrations.AddField(
            model_name='product',
            name='harddisk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.harddisk'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.processor'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.ram'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.storage'),
        ),
    ]
