# Generated by Django 3.2 on 2021-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210411_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='name',
            field=models.FloatField(max_length=20),
        ),
    ]
