# Generated by Django 3.2 on 2021-04-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='name',
            new_name='inch',
        ),
    ]
