# Generated by Django 3.2 on 2021-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_name_display_inch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.SlugField(max_length=20),
        ),
    ]
