# Generated by Django 3.2 on 2021-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_processor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.SlugField(max_length=20),
        ),
    ]
