# Generated by Django 3.2 on 2021-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_ram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.SlugField(max_length=20),
        ),
    ]
