# Generated by Django 3.2 on 2021-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
